version: '3.8'

services:
  twitch-oauth:
    build: ./app
    container_name: twitch-oauth
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=drmax03.de
      - LETSENCRYPT_HOST=drmax03.de
      - LETSENCRYPT_EMAIL=deine@email.de
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
